version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X github.com/Fanteria/EANBaker/values.Version={{.Version}}
      - -X github.com/Fanteria/EANBaker/values.Commit={{.Commit}}
      - -X github.com/Fanteria/EANBaker/values.Date={{.Date}}

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^wip$"
      - "^build:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Refactoring
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: Dependencies
      regexp: '^.*?(build|deps)(\([[:word:]]+\))??!?:.+$'
      order: 4
    - title: Other Changes
      order: 999
